//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLy002
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitietHD
    {
        public string MaHD { get; set; }
        public string MaHang { get; set; }
        public double Soluong { get; set; }
        public double Dongia { get; set; }
        public double Giamgia { get; set; }
        public double Thanhtien { get; set; }
    
        public virtual Hang Hang { get; set; }
        public virtual HoaDon HoaDon { get; set; }
    }
}
